### ISSUE TITLE
Possibly change rewards

### ISSUE THREAD

**Issue by aplarson** [gconen/RocketStarter#2]
I'm not a Kickstarter user, so I may be off the mark, but aren't rewards usually just given for passing a certain support threshold? If so, you probably want to remove `reward_id` from pledges and institute a table that would join users to the rewards they've achieved. Could be updated whenever a pledge is made.

**Comment by gconen** [comment]
There may be multiple rewards for a given threshold, and people are free to choose rewards for lower thresholds if they want to give more but prefer the lower reward. However, all that can (and probably more clearly) using a join table just for that instead of embedding the data in rewards.
